-- ═══ OPERATING COSTS ═══════════════════════════════════════════════════════
--
-- 02-POS-SPEC.md §2 (`opcosts`): "All 16 expense categories, recurring costs,
-- overhead allocation." 08-BUILD-STAGES §18.
--
-- Everything below gross profit currently arrives in this system as a SIDE
-- EFFECT of something else: cost of sales from a sale, wages from a payroll
-- run, stock variance from a count. Rent, electricity, the licence and the pest
-- contract have had accounts in the chart since day one and no way to reach
-- them, so net profit has been gross profit minus whatever happened to post.
--
-- TWO IDEAS, AND THE SECOND IS THE ONE THAT MATTERS.
--
-- A RECURRING COST is a schedule, not a diary reminder. Rent is due on the
-- first of every month whether or not anybody opens the screen, and a system
-- that only knows about costs somebody remembered to type produces a P&L that
-- flatters every month nobody was paying attention.
--
-- A SPREAD COST is the overhead allocation §2 asks for. An annual licence paid
-- in January is not January's cost; it is a twelfth of it, twelve times over.
-- Charged to the month it was paid, January reads as a disaster and the other
-- eleven read as better than they were — and a restaurant that manages by
-- monthly P&L will act on both. So a spread cost is capitalised to 1200 Prepaid
-- expenses (an account that has existed in the chart and never been used) and
-- released a period at a time.
DO $$
DECLARE o record;
BEGIN
  FOR o IN SELECT schema_name, db_role FROM chain.outlet LOOP
    EXECUTE format($q$
      CREATE TABLE IF NOT EXISTS %1$I.expense (
        id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        at        timestamptz NOT NULL DEFAULT now(),
        spent_on  date NOT NULL,
        account_code text NOT NULL REFERENCES %1$I.account(code),
        amount    numeric(12,2) NOT NULL CHECK (amount > 0),
        supplier_id uuid,
        note      text,
        -- How it was settled. 'credit' means it is owed — accounts payable —
        -- which is a different fact from having paid for it, and the P&L is the
        -- same either way while the cash flow is not.
        method    text NOT NULL DEFAULT 'credit'
                  CHECK (method IN ('cash','bank','credit')),
        -- Set when this row was generated by a schedule rather than typed, so
        -- a schedule can never post the same period twice.
        recurring_id uuid,
        period_key text,
        -- A SPREAD cost sits on 1200 until it is released. `spread_months` is
        -- how many periods it belongs to; NULL is an ordinary expense.
        spread_months int CHECK (spread_months IS NULL OR spread_months > 1),
        released_months int NOT NULL DEFAULT 0,
        -- The last period this cost was released FOR ('YYYY-MM'), so running
        -- the month-end release twice cannot charge the month twice. Nothing
        -- downstream would catch that: a duplicate is self-consistent and the
        -- trial balance goes on balancing.
        released_upto text,
        by_staff  uuid,
        UNIQUE (recurring_id, period_key)
      );
      CREATE INDEX IF NOT EXISTS expense_when ON %1$I.expense (spent_on DESC);
      CREATE INDEX IF NOT EXISTS expense_unreleased ON %1$I.expense (spent_on)
        WHERE spread_months IS NOT NULL;

      CREATE TABLE IF NOT EXISTS %1$I.recurring_cost (
        id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        account_code text NOT NULL REFERENCES %1$I.account(code),
        amount    numeric(12,2) NOT NULL CHECK (amount > 0),
        cadence   text NOT NULL CHECK (cadence IN ('weekly','monthly','annual')),
        -- The day it falls due: 1-7 for weekly (Monday is 1), 1-31 monthly,
        -- 1-366 for annual as a day of the year.
        due_day   int NOT NULL,
        starts_on date NOT NULL,
        ends_on   date,
        supplier_id uuid,
        note      text,
        method    text NOT NULL DEFAULT 'credit'
                  CHECK (method IN ('cash','bank','credit')),
        spread_months int CHECK (spread_months IS NULL OR spread_months > 1),
        active    boolean NOT NULL DEFAULT true,
        set_by    uuid, set_at timestamptz NOT NULL DEFAULT now()
      );
      ALTER TABLE %1$I.expense ADD COLUMN IF NOT EXISTS released_upto text;
    $q$, o.schema_name);

    -- The grant is the other half of adding a table. See migration 014.
    EXECUTE format('GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA %I TO %I',
                   o.schema_name, o.db_role);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO %I',
                   o.schema_name, o.db_role);
    -- A schedule that was set up wrongly is deleted; a posted expense never is.
    EXECUTE format('GRANT DELETE ON %I.recurring_cost TO %I', o.schema_name, o.db_role);
  END LOOP;
END $$;
